config/routes.rb
Rails.application.routes.draw do
  devise_for :userauths 
  resources :probeconfigids do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newprobeconfigid
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :iterations do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newiteration
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :dot_probes do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newdot_probe
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :answers do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newanswer
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :surveys do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newsurvey
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :consents do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newconsent
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :users do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newuser
      patch :update
      put :update
      delete :destroy
    end
  end

=begin
  get "/users" index
  post "/users" create 
  delete "/users" delete
  get "/users/:id" show
  get "/users/new" new 
  get "/users/:id/edit" edit
  patch "/users/:id" update
  put "/users/:id" update
=end

  root 'users#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def newanswer
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:survey_id, :question, :answer, :elapsed_time)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :survey_id %><br>
    <%= f.number_field :survey_id %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :elapsed_time %><br>
    <%= f.text_field :elapsed_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Survey</th>
      <th>Question</th>
      <th>Answer</th>
      <th>Elapsed time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.survey_id %></td>
        <td><%= answer.question %></td>
        <td><%= answer.answer %></td>
        <td><%= answer.elapsed_time %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Survey:</strong>
  <%= @answer.survey_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<p>
  <strong>Elapsed time:</strong>
  <%= @answer.elapsed_time %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>