config/routes.rb
Rails.application.routes.draw do
  devise_for :userauths 
  resources :probeconfigids do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newprobeconfigid
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :iterations do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newiteration
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :dot_probes do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newdot_probe
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :answers do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newanswer
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :surveys do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newsurvey
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :consents do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newconsent
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :users do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newuser
      patch :update
      put :update
      delete :destroy
    end
  end

=begin
  get "/users" index
  post "/users" create 
  delete "/users" delete
  get "/users/:id" show
  get "/users/new" new 
  get "/users/:id/edit" edit
  patch "/users/:id" update
  put "/users/:id" update
=end

  root 'users#index'

end

app/models/iteration.rb
class Iteration < ActiveRecord::Base
end

app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
  before_action :set_iteration, only: [:show, :edit, :update, :destroy]

  # GET /iterations
  # GET /iterations.json
  def index
    @iterations = Iteration.all
  end

  # GET /iterations/1
  # GET /iterations/1.json
  def show
  end

  # GET /iterations/new
  def new
    @iteration = Iteration.new
  end

  # GET /iterations/1/edit
  def edit
  end

  # POST /iterations
  # POST /iterations.json
  def newiteration
    @iteration = Iteration.new(iteration_params)

    respond_to do |format|
      if @iteration.save
        format.html { redirect_to @iteration, notice: 'Iteration was successfully created.' }
        format.json { render :show, status: :created, location: @iteration }
      else
        format.html { render :new }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iterations/1
  # PATCH/PUT /iterations/1.json
  def update
    respond_to do |format|
      if @iteration.update(iteration_params)
        format.html { redirect_to @iteration, notice: 'Iteration was successfully updated.' }
        format.json { render :show, status: :ok, location: @iteration }
      else
        format.html { render :edit }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iterations/1
  # DELETE /iterations/1.json
  def destroy
    @iteration.destroy
    respond_to do |format|
      format.html { redirect_to iterations_url, notice: 'Iteration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iteration
      @iteration = Iteration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iteration_params
      params.require(:iteration).permit(:dot_probe_id, :img_left, :img_right, :elapsed_time, :touch_position)
    end
end

app/helpers/iterations_helper.rb
module IterationsHelper
end

app/views/iterations/_form.html.erb
<%= form_for(@iteration) do |f| %>
  <% if @iteration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

      <ul>
      <% @iteration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dot_probe_id %><br>
    <%= f.number_field :dot_probe_id %>
  </div>
  <div class="field">
    <%= f.label :img_left %><br>
    <%= f.text_field :img_left %>
  </div>
  <div class="field">
    <%= f.label :img_right %><br>
    <%= f.text_field :img_right %>
  </div>
  <div class="field">
    <%= f.label :elapsed_time %><br>
    <%= f.text_field :elapsed_time %>
  </div>
  <div class="field">
    <%= f.label :touch_position %><br>
    <%= f.text_field :touch_position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/iterations/edit.html.erb
<h1>Editing Iteration</h1>

<%= render 'form' %>

<%= link_to 'Show', @iteration %> |
<%= link_to 'Back', iterations_path %>

app/views/iterations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Iterations</h1>

<table>
  <thead>
    <tr>
      <th>Dot probe</th>
      <th>Img left</th>
      <th>Img right</th>
      <th>Elapsed time</th>
      <th>Touch position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iterations.each do |iteration| %>
      <tr>
        <td><%= iteration.dot_probe_id %></td>
        <td><%= iteration.img_left %></td>
        <td><%= iteration.img_right %></td>
        <td><%= iteration.elapsed_time %></td>
        <td><%= iteration.touch_position %></td>
        <td><%= link_to 'Show', iteration %></td>
        <td><%= link_to 'Edit', edit_iteration_path(iteration) %></td>
        <td><%= link_to 'Destroy', iteration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iteration', new_iteration_path %>

app/views/iterations/new.html.erb
<h1>New Iteration</h1>

<%= render 'form' %>

<%= link_to 'Back', iterations_path %>

app/views/iterations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dot probe:</strong>
  <%= @iteration.dot_probe_id %>
</p>

<p>
  <strong>Img left:</strong>
  <%= @iteration.img_left %>
</p>

<p>
  <strong>Img right:</strong>
  <%= @iteration.img_right %>
</p>

<p>
  <strong>Elapsed time:</strong>
  <%= @iteration.elapsed_time %>
</p>

<p>
  <strong>Touch position:</strong>
  <%= @iteration.touch_position %>
</p>

<%= link_to 'Edit', edit_iteration_path(@iteration) %> |
<%= link_to 'Back', iterations_path %>