config/routes.rb
Rails.application.routes.draw do
  devise_for :userauths 
  resources :probeconfigids do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newprobeconfigid
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :iterations do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newiteration
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :dot_probes do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newdot_probe
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :answers do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newanswer
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :surveys do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newsurvey
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :consents do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newconsent
      patch :update
      put :update
      delete :destroy
    end
  end
  resources :users do
    collection do
      get :index
      get :show 
      get :new
      get :edit
      post :newuser
      patch :update
      put :update
      delete :destroy
    end
  end

=begin
  get "/users" index
  post "/users" create 
  delete "/users" delete
  get "/users/:id" show
  get "/users/new" new 
  get "/users/:id/edit" edit
  patch "/users/:id" update
  put "/users/:id" update
=end

  root 'users#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	has_belong :surveys
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def newsurvey
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:user_id, :start_date, :end_date)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.user_id %></td>
        <td><%= survey.start_date %></td>
        <td><%= survey.end_date %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @survey.user_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @survey.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @survey.end_date %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>